### ISSUE TITLE
Let's add Xamarin license installation and removal?

### ISSUE THREAD

**Issue by ghuntley** [Redth/Cake.Xamarin#1]
Hey Redth,

Would you take a pull-request that implements:

> https://github.com/reactiveui/ReactiveUI/blob/ci/script/licenseinstall
> https://github.com/reactiveui/ReactiveUI/blob/ci/script/licenseremove

What do you want the methods to be called, signatures and what exceptions should be thrown (if any)

    void RemoveLicenses() // removes all licenses from build host, may throw if we are not logged in? (imho no)
    T InstallLicenses(string username, string password) // installs all licenses available onto the build host may throw exception if max amount of licenses installed.

    ghuntley-macbook-pro:~ ghuntley$ "/Applications/Xamarin Studio.app/Contents/MacOS/mdtool" account login
    Xamarin Account Tool
    Username: ghuntley@ghuntley.com
    Password:
    Logging in...
    Checking licenses...

    Licenses:
        Xamarin.Android: Business (2016-07-11 00:56:47Z)
        Xamarin.iOS: Business (2016-07-11 00:56:47Z)
        Xamarin.Mac: Business (2016-07-11 00:56:47Z)

Additionally for LicenseStatus what should we publicly expose and what exceptions should be thrown (if any)? 

    T LicenseStatus()  // displays which products are licensed on the build host, may throw if not logged in.

    ghuntley-macbook-pro:~ ghuntley$ "/Applications/Xamarin Studio.app/Contents/MacOS/mdtool" account info
    Xamarin Account Tool
    Not logged in

    ghuntley-macbook-pro:~ ghuntley$ "/Applications/Xamarin Studio.app/Contents/MacOS/mdtool" account info
    Xamarin Account Tool
    Account:
        Geoffrey Huntley <ghuntley@ghuntley.com>

    Checking licenses...

    Licenses:
        Xamarin.Android: Business (2016-07-11 00:56:47Z)
        Xamarin.iOS: Business (2016-07-11 00:56:47Z)
        Xamarin.Mac: Business (2016-07-11 00:56:47Z)

**Comment by Redth** [comment]
Sorry for dragging my heels here, but I do believe this is no longer necessary :)
