### ISSUE TITLE
Android Additional Task - Publish APK

### ISSUE THREAD

**Issue by louisfischer** [Redth/Cake.Xamarin#2]
Request enhancements for Additional Android tasks.
Publish APK task for Alpha, Beta, Rollout, and Productiion scenerios

**Comment by rroman81** [comment]
+1 on that one.

**Comment by Redth** [comment]
That's a pretty big ask :)

I don't think I can tie into the built in publish workflow Xamarin offers in the IDE.

I'd suggest this is better as its own addin (Maybe Cake.GooglePlayStore ?) which would also be useful to Android java devs.

I'm going to say this is out of scope for this addin, sorry :(
