### ISSUE TITLE
Cake NuGet package is very out-of-date

### ISSUE THREAD

**Issue by agc93** [Redth/Cake.Xamarin#7]
This project is dependent on Cake 0.10.1, which is now 8 months behind. Since then, there's been changes to the `Tool<TSettings>` signature, as well as quite a few other changes and improvements.

Once 0.18.0 comes out (soon), I can have a look at a PR for updating this, unless you have any objections @Redth ?

**Comment by Redth** [comment]
That would be helpful, thanks!

**Comment by jzeferino** [comment]
@agc93 @Redth Im ready to help in that migration.

**Comment by Redth** [comment]
I updated master to use cake 0.17
